import AppKit
import CryptoKit
import Foundation
import Observation
import SwiftData
import UniformTypeIdentifiers

/// Polls `NSPasteboard.general` for changes and persists new entries.
///
/// macOS provides no notification for pasteboard mutations; the supported
/// pattern is to compare `changeCount` periodically. We poll every 0.5 s,
/// which is the value used by Maccy and similar tools and is effectively
/// invisible in CPU profiles.
@MainActor
@Observable
final class ClipboardMonitor {
    /// How often to poll the pasteboard.
    private let pollInterval: TimeInterval = 0.5

    /// Maximum number of unpinned items kept in history. Pinned items always survive.
    var historyLimit: Int {
        get { UserDefaults.standard.integer(forKey: SettingsKey.historyLimit).nonZero
              ?? SettingsKey.defaultHistoryLimit }
        set {
            UserDefaults.standard.set(newValue, forKey: SettingsKey.historyLimit)
        }
    }

    /// Bundle IDs whose copies should be ignored (e.g. password managers).
    /// In v1 this is hard-coded; SettingsView will gain a UI later.
    private let ignoredBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal"
    ]

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let modelContext: ModelContext

    init(modelContext: ModelContext) {
        self.modelContext = modelContext
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.tick()
            }
        }
        // Common runloop mode keeps polling while menus / popovers are open.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Polling

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Respect "Concealed" / "Transient" markers used by password managers
        // and other privacy-sensitive copies. See nspasteboard.org for the convention.
        let types = pasteboard.types ?? []
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        let bundleID = frontApp?.bundleIdentifier
        if let bundleID, ignoredBundleIDs.contains(bundleID) { return }

        // Image takes priority over text: most image copies also include a
        // path/text fallback that we don't want to capture twice.
        if let (data, width, height) = readImage(from: pasteboard, types: types) {
            insertImage(data: data, width: width, height: height, sourceBundleID: bundleID)
            return
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            insertText(text, sourceBundleID: bundleID)
        }
    }

    // MARK: - Read helpers

    /// Try to extract an NSImage from the pasteboard and re-encode it as PNG so
    /// every item is stored in a single canonical format. Returns the PNG data
    /// plus the image's natural pixel size.
    private func readImage(
        from pb: NSPasteboard,
        types: [NSPasteboard.PasteboardType]
    ) -> (data: Data, width: Int, height: Int)? {
        if let data = readImageData(from: pb, types: types) {
            return pngData(fromImageData: data)
        }

        if let url = readImageFileURL(from: pb),
           let image = NSImage(contentsOf: url) {
            return pngData(from: image)
        }

        if types.contains(where: isImagePasteboardType),
           let image = NSImage(pasteboard: pb) {
            return pngData(from: image)
        }

        return nil
    }

    private func readImageData(
        from pb: NSPasteboard,
        types: [NSPasteboard.PasteboardType]
    ) -> Data? {
        let preferredTypes: [NSPasteboard.PasteboardType] = [
            .png,
            .tiff,
            NSPasteboard.PasteboardType("public.jpeg"),
            NSPasteboard.PasteboardType("public.heic"),
            NSPasteboard.PasteboardType("public.heif"),
            NSPasteboard.PasteboardType("com.compuserve.gif"),
            NSPasteboard.PasteboardType("org.webmproject.webp")
        ]

        for type in preferredTypes where types.contains(type) {
            if let data = pb.data(forType: type) {
                return data
            }
        }

        for type in types where isImagePasteboardType(type) {
            if let data = pb.data(forType: type) {
                return data
            }
        }

        return nil
    }

    private func readImageFileURL(from pb: NSPasteboard) -> URL? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true
        ]
        let objects = pb.readObjects(forClasses: [NSURL.self], options: options) ?? []
        let urls = objects.compactMap { object -> URL? in
            if let url = object as? URL { return url }
            if let url = object as? NSURL { return url as URL }
            return nil
        }
        return urls.first(where: isImageFileURL)
    }

    private func isImageFileURL(_ url: URL) -> Bool {
        guard url.isFileURL else { return false }
        if let type = try? url.resourceValues(forKeys: [.contentTypeKey]).contentType {
            return type.conforms(to: .image)
        }
        return NSImage(contentsOf: url) != nil
    }

    private func isImagePasteboardType(_ type: NSPasteboard.PasteboardType) -> Bool {
        UTType(type.rawValue)?.conforms(to: .image) == true
    }

    private func pngData(fromImageData data: Data) -> (data: Data, width: Int, height: Int)? {
        if let rep = NSBitmapImageRep(data: data),
           let png = rep.representation(using: .png, properties: [:]) {
            return (png, rep.pixelsWide, rep.pixelsHigh)
        }

        guard let image = NSImage(data: data) else { return nil }
        return pngData(from: image)
    }

    private func pngData(from image: NSImage) -> (data: Data, width: Int, height: Int)? {
        if let rep = image.representations
            .compactMap({ $0 as? NSBitmapImageRep })
            .max(by: { lhs, rhs in
                (lhs.pixelsWide * lhs.pixelsHigh) < (rhs.pixelsWide * rhs.pixelsHigh)
            }),
           let png = rep.representation(using: .png, properties: [:]) {
            return (png, rep.pixelsWide, rep.pixelsHigh)
        }

        guard let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) else {
            return nil
        }
        let rep = NSBitmapImageRep(cgImage: cgImage)
        rep.size = image.size
        guard let png = rep.representation(using: .png, properties: [:]) else { return nil }
        return (png, rep.pixelsWide, rep.pixelsHigh)
    }

    // MARK: - Persistence

    /// Insert a text entry only if the exact text is not already in history.
    private func insertText(_ text: String, sourceBundleID: String?) {
        let descriptor = FetchDescriptor<ClipboardItem>(
            predicate: #Predicate { $0.text == text && $0.imageData == nil }
        )
        if let matches = try? modelContext.fetch(descriptor),
           let existing = matches.first {
            if existing.sourceBundleID == nil, sourceBundleID != nil {
                existing.sourceBundleID = sourceBundleID
                try? modelContext.save()
            }
            return
        }

        let item = ClipboardItem(text: text, sourceBundleID: sourceBundleID)
        modelContext.insert(item)
        prune()
        try? modelContext.save()
    }

    /// Insert an image entry only if the PNG hash is not already in history.
    private func insertImage(data: Data, width: Int, height: Int, sourceBundleID: String?) {
        let hash = sha256(data)

        let descriptor = FetchDescriptor<ClipboardItem>(
            predicate: #Predicate { $0.imageHash == hash }
        )
        if let matches = try? modelContext.fetch(descriptor),
           let existing = matches.first {
            var changed = false
            if existing.sourceBundleID == nil, sourceBundleID != nil {
                existing.sourceBundleID = sourceBundleID
                changed = true
            }
            if existing.imageWidth == nil {
                existing.imageWidth = width
                changed = true
            }
            if existing.imageHeight == nil {
                existing.imageHeight = height
                changed = true
            }
            if changed {
                try? modelContext.save()
            }
            return
        }

        let item = ClipboardItem(
            text: "",
            imageData: data,
            imageHash: hash,
            imageWidth: width,
            imageHeight: height,
            sourceBundleID: sourceBundleID
        )
        modelContext.insert(item)
        prune()
        try? modelContext.save()
    }

    private func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Drop the oldest unpinned items beyond `historyLimit`.
    private func prune() {
        let descriptor = FetchDescriptor<ClipboardItem>(
            predicate: #Predicate { !$0.isPinned },
            sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
        )
        guard let items = try? modelContext.fetch(descriptor) else { return }
        guard items.count > historyLimit else { return }
        for item in items[historyLimit...] {
            modelContext.delete(item)
        }
    }

    /// Programmatically clear all history (pinned items included).
    func clearAll() {
        let descriptor = FetchDescriptor<ClipboardItem>()
        guard let items = try? modelContext.fetch(descriptor) else { return }
        for item in items { modelContext.delete(item) }
        try? modelContext.save()
    }

    /// Delete a single item.
    func delete(_ item: ClipboardItem) {
        modelContext.delete(item)
        try? modelContext.save()
    }
}

private extension Int {
    /// Treat 0 (the default for an unset UserDefaults integer) as "no value".
    var nonZero: Int? { self == 0 ? nil : self }
}
