import AppKit
import Carbon.HIToolbox
import CoreGraphics

/// Writes a `ClipboardItem` to the system pasteboard and synthesises a `Cmd+V`
/// keystroke so it lands in whichever app currently has focus.
///
/// The `CGEvent` post requires the user to grant Accessibility access in
/// System Settings; `PermissionsService` exposes the trust check.
@MainActor
enum PasteService {
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Write the item to the pasteboard and (optionally) simulate Cmd+V to paste
    /// into the frontmost application.
    static func paste(_ item: ClipboardItem, autoPaste: Bool = true) {
        write(item)

        guard autoPaste else { return }
        guard PermissionsService.isAccessibilityTrusted else { return }

        // Defer one runloop tick so the popover has finished closing and key
        // focus has returned to the previously-frontmost app.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            sendCommandV()
        }
    }

    /// Write item contents to the pasteboard without pasting.
    static func write(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if let data = item.imageData {
            let image = NSImage(data: data)
            if let image {
                _ = pb.writeObjects([image])
            }
            // Write both PNG (for modern apps) and TIFF (for AppKit-era apps).
            pb.setData(data, forType: .png)
            if let tiff = image?.tiffRepresentation {
                pb.setData(tiff, forType: .tiff)
            }
        } else {
            pb.setString(item.text, forType: .string)
        }
        pb.setData(Data([0]), forType: autoGeneratedType)
    }

    // MARK: - Synthetic keystroke

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKey = CGKeyCode(kVK_ANSI_V)

        let down = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true)
        down?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)

        let up = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false)
        up?.flags = .maskCommand
        up?.post(tap: .cghidEventTap)
    }
}
